export const DISMISS_ERROR_MESSAGE = "DISMISS_ERROR_MESSAGE"

export const DISMISS_SUCCESS_MESSAGE = "DISMISS_SUCCESS_MESSAGE"

export const FLASH_ERROR_MESSAGE = "FLASH_ERROR_MESSAGE";

export const FLASH_SUCCESS_MESSAGE = "FLASH_SUCCESS_MESSAGE";

export const UPDATE_LOADING = "UPDATE_LOADING";

export const DISMISS_INFO_MESSAGE = "DISMISS_INFO_MESSAGE";

export const FLASH_INFO_MESSAGE = "FLASH_INFO_MESSAGE";